# Generated by Django 3.2 on 2021-04-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20210413_0733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCategory',
        ),
    ]
