# Generated by Django 3.2 on 2021-04-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
