# Generated by Django 3.2 on 2021-05-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(default='cloud.jpg', upload_to='images'),
        ),
    ]
