# Generated by Django 3.2 on 2021-04-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
