# Generated by Django 3.2 on 2021-05-01 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_subcategory_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_subcategory', to='shops.shop')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_subcategory', to='shops.subcategory')),
            ],
        ),
    ]
