# Generated by Django 3.2 on 2021-04-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_subcategory_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shops.category'),
        ),
    ]
