# Generated by Django 3.2 on 2021-04-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_subcategory_category'),
        ('products', '0002_auto_20210428_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.subcategory'),
        ),
    ]
