# Generated by Django 3.2 on 2021-04-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20210415_2004'),
        ('products', '0002_order_product_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='shops.subcategory'),
        ),
    ]
