# Generated by Django 3.2 on 2021-05-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_person',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
    ]
