# Generated by Django 3.2 on 2021-05-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delivery_person_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Title',
            new_name='productName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
