# Generated by Django 3.2 on 2021-05-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210502_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='Title',
        ),
    ]
