# Generated by Django 3.2 on 2021-05-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
    ]
